{% set name = "hydromt" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt-{{ version }}.tar.gz
  sha256: bc1c2d766ac4931d0eb6416526364f474edc7d3ae3b6d1f70905df18f51abf70

build:
  number: 0
  noarch: python
  entry_points:
    - hydromt = hydromt.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - affine
    - bottleneck
    - click
    - dask
    - entrypoints
    - fsspec
    - fiona==1.8.22
    - gdal >=3.1
    - geopandas >=0.10
    - netcdf4
    - numpy>=1.20
    - numba
    - openpyxl
    - packaging
    - pandas
    - pyflwdir >=0.5.4
    - pyproj
    - python >=3.9
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely >=2.0.0
    - universal_pathlib
    - xarray
    - xmltodict
    - zarr

test:
  imports:
    - hydromt
    - hydromt.cli
  commands:
    - pip check
    - hydromt --help
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt/
  summary: 'HydroMT: Build and analyze models like a data-wizard!'
  dev_url: https://github.com/Deltares/hydromt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - savente93
    - DirkEilander
    - hboisgon
